#!/bin/bash

if [ $# -ne 1 ];
then
    echo "$0 [path/to/executable]"
    exit
fi

EXE=$1
LINK_NAME=$(realpath ~)/.local/bin/$(basename $1)

if [ "${EXE:0:1}" = "/" ]
then
        TARGET=$1
else
        TARGET=$(pwd)/$1
fi

echo LINK_NAME=$LINK_NAME, TARGET=$TARGET

ln -f -s $TARGET $LINK_NAME

chmod +x $LINK_NAME
